apiVersion: v1
kind: ConfigMap
metadata:
    name: brainfuck
data:
    stdout:
      {{- $env := dict "program" .Values.program "input" .Values.stdin "wrap" .Values.wrap }} 
      {{- include "bf.run" $env | toYaml}}
